# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXLtvPifd-qrue-1X8EoscVjPnRvHer7
"""

# -------------------------------
# FULL ASSIGNMENT IN ONE CELL
# -------------------------------

import pandas as pd
import matplotlib.pyplot as plt

# 1️⃣ Load Dataset
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

# 2️⃣ Save dataset to file
df.to_csv("my_data.csv", index=False)

# 3️⃣ Process / Clean
print("Before cleaning:")
print(df.isnull().sum())
df = df.dropna()
print("\nAfter cleaning:")
print(df.isnull().sum())

# 4️⃣ Visualization
plt.figure()
plt.scatter(df["total_bill"], df["tip"])
plt.title("Total Bill vs Tip")
plt.xlabel("Total Bill")
plt.ylabel("Tip")
plt.show()

# Show first few rows to prove it worked
df.head()